# mtr_script_settings.yaml
#
# General settings for MTR monitor script

# Global logging
log_directory: /opt/scripts/MTR_WEB/logs/

# RRD and graphing
rrd_directory: /opt/scripts/MTR_WEB/data/
graph_output_directory: /opt/scripts/MTR_WEB/html/graphs/
max_hops: 30
graph_width: 800
graph_height: 200

# Traceroute data
trace_directory: /opt/scripts/MTR_WEB/traces/

# Monitoring interval
interval_seconds: 60

# Auto-refresh in HTML pages
html_auto_refresh_seconds: 0

# Log display in HTML pages
log_lines_display: 50

# Graph time ranges (shown as tabs in HTML)
graph_time_ranges:
  - label: "1h"
    seconds: 3600
  - label: "6h"
    seconds: 21600
  - label: "12h"
    seconds: 43200
  - label: "24h"
    seconds: 86400


# Cleanup retention settings (in days)
retention:
  rrd_days: 30             # Keep RRD files for 30 days
  logs_days: 60            # Keep log files for 60 days
  traceroute_days: 45      # Keep traceroute JSONs for 45 days
  graphs_days: 7           # Keep PNG graphs for 7 days
  html_days: 10            # Keep old HTML files for 10 days

# Optional: enable/disable fping in index.html
enable_fping_check: true


# === Alerting (Not Yet Implemented) ===
# alert_email_to: "alerts@example.com"
# loss_threshold: 50              # % packet loss that triggers an alert
# debounce_seconds: 300           # Minimum interval between alerts per IP
