# mtr_script_settings.yaml
#
# General settings for MTR monitor script

# === Logging ===
log_directory: /opt/scripts/MTR_WEB/logs/

# === RRD and Graphing ===
rrd_directory: /opt/scripts/MTR_WEB/data/
graph_output_directory: /opt/scripts/MTR_WEB/html/graphs/
max_hops: 30
graph_width: 800
graph_height: 200

# Define the structure of RRD files
rrd:
  step: 60               # One data point per minute
  heartbeat: 120         # Accept data if within 120s
  data_sources:
    - name: avg
      type: GAUGE
      min: 0
      max: U
    - name: last
      type: GAUGE
      min: 0
      max: U
    - name: best
      type: GAUGE
      min: 0
      max: U
    - name: loss
      type: GAUGE
      min: 0
      max: 100
  rras:
    - cf: AVERAGE
      xff: 0.5
      step: 1
      rows: 43200      # 30 days of 60s data
    - cf: AVERAGE
      xff: 0.5
      step: 5
      rows: 51840      # 180 days of 5-min averages
    - cf: AVERAGE
      xff: 0.5
      step: 30
      rows: 52560      # ~3 years of 30-min averages

# === Traceroute ===
traceroute_directory: /opt/scripts/MTR_WEB/traces/

# === Monitoring Interval ===
interval_seconds: 60

# === HTML Display Settings ===
html_auto_refresh_seconds: 0
log_lines_display: 50

graph_time_ranges:
  - label: "1h"
    seconds: 3600
  - label: "6h"
    seconds: 21600
  - label: "12h"
    seconds: 43200
  - label: "24h"
    seconds: 86400

# === Cleanup Retention (in days) ===
retention:
  rrd_days: 30
  logs_days: 60
  traceroute_days: 45
  graphs_days: 7
  html_days: 10

# === Optional FPing Status in index.html ===
enable_fping_check: true

# === Alerting (future) ===
# alert_email_to: "alerts@example.com"
# loss_threshold: 50
# debounce_seconds: 300
