# mtr_script_settings.yaml
#
# General settings for MTR monitor script

interval_seconds: 60
log_directory: logs/
rrd_directory: data/
graph_output_directory: html/graphs/
retention_days: 30
max_hops: 30
log_lines_to_show: 30
