# mtr_script_settings.yaml
#
# General settings for MTR monitor script

# === Logging ===
log_directory: /opt/scripts/MTR_WEB/logs/

# Per-script log levels (used by setup_logger)
logging_levels:
  controller: INFO
  mtr_monitor: DEBUG
  graph_generator: INFO
  html_generator: INFO
  html_builder: INFO
  index_generator: INFO

# === RRD and Graphing ===
rrd_directory: /opt/scripts/MTR_WEB/data/
graph_output_directory: /opt/scripts/MTR_WEB/html/graphs/
max_hops: 30
graph_width: 800
graph_height: 200

rrd:
  step: 60
  heartbeat: 120
  data_sources:
    - name: avg
      type: GAUGE
      min: 0
      max: U
    - name: last
      type: GAUGE
      min: 0
      max: U
    - name: best
      type: GAUGE
      min: 0
      max: U
    - name: loss
      type: GAUGE
      min: 0
      max: 100
  rras:
    - cf: AVERAGE
      xff: 0.5
      step: 1
      rows: 43200
    - cf: AVERAGE
      xff: 0.5
      step: 5
      rows: 51840
    - cf: AVERAGE
      xff: 0.5
      step: 30
      rows: 52560

# === Traceroute ===
traceroute_directory: /opt/scripts/MTR_WEB/traces/

# === Monitoring ===
interval_seconds: 60

# === HTML Settings ===
html_auto_refresh_seconds: 0
log_lines_display: 50

graph_time_ranges:
  - label: "1h"
    seconds: 3600
  - label: "6h"
    seconds: 21600
  - label: "12h"
    seconds: 43200
  - label: "24h"
    seconds: 86400

# === Cleanup Retention ===
retention:
  rrd_days: 30
  logs_days: 60
  traceroute_days: 45
  graphs_days: 7
  html_days: 10

# === Optional FPing in index.html ===
enable_fping_check: true

# === Alerting (Not yet implemented) ===
# alert_email_to: "alerts@example.com"
# loss_threshold: 50
# debounce_seconds: 300
