# mtr_script_settings.yaml
#
# General settings for MTR monitor script

# === Logging ===
log_directory: /opt/scripts/MTR_WEB/logs/

# Per-script log levels (used by setup_logger)
logging_levels:
  controller: INFO
  mtr_monitor: DEBUG
  graph_generator: INFO
  html_generator: INFO
  html_builder: INFO
  index_generator: INFO

# === RRD and Graphing ===
rrd_directory: /opt/scripts/MTR_WEB/data/
graph_output_directory: /opt/scripts/MTR_WEB/html/graphs/
max_hops: 30
graph_width: 800
graph_height: 200


#step and rows determine how long your data is retained.
#You can mix different cf functions (e.g. MAX to highlight spikes).
#When updating this config:
#It only affects newly created RRDs.
#Existing .rrd files must be deleted and recreated to apply new RRA settings (or use rrdtool tune but that's more advanced and limited).

rrd:
  step: 60         # every 60 seconds a new sample
  heartbeat: 120   # max expected interval between samples
  data_sources:
    - name: avg
      type: GAUGE
      min: 0
      max: 1000
    - name: last
      type: GAUGE
      min: 0
      max: 1000
    - name: best
      type: GAUGE
      min: 0
      max: 1000
    - name: loss
      type: GAUGE
      min: 0
      max: 100

  rras:
    - cf: AVERAGE
      xff: 0.5
      step: 1         # 1 PDP (every minute)
      rows: 1440      # store 24 hours of 1-minute data
    - cf: AVERAGE
      xff: 0.5
      step: 5         # 5 minutes
      rows: 2016      # ~1 week of 5-min averages
    - cf: AVERAGE
      xff: 0.5
      step: 30        # 30 minutes
      rows: 1440      # ~1 month of 30-min data
    - cf: MAX
      xff: 0.5
      step: 30
      rows: 1440

# === Traceroute ===
traceroute_directory: /opt/scripts/MTR_WEB/traces/

# === Monitoring ===
interval_seconds: 60

# === HTML Settings ===
html_auto_refresh_seconds: 0
log_lines_display: 50

graph_time_ranges:
  - label: "1h"
    seconds: 3600
  - label: "6h"
    seconds: 21600
  - label: "12h"
    seconds: 43200
  - label: "24h"
    seconds: 86400

# === Cleanup Retention ===
retention:
  rrd_days: 30
  logs_days: 60
  traceroute_days: 45
  graphs_days: 7
  html_days: 10

# === Optional FPing in index.html ===
enable_fping_check: true

# === Alerting (Not yet implemented) ===
# alert_email_to: "alerts@example.com"
# loss_threshold: 50
# debounce_seconds: 300
