# mtr_script_settings.yaml
#
# General settings for MTR monitor script

interval_seconds: 60
log_directory: /opt/scripts/MTR_WEB/logs/
rrd_directory: /opt/scripts/MTR_WEB/data/
graph_output_directory: /opt/scripts/MTR_WEB/html/graphs/
retention_days: 30
max_hops: 30
log_lines_to_show: 30
trace_directory: /opt/scripts/MTR_WEB/traces
enable_fping_check: true
html_auto_refresh_seconds: 60
graph_width: 600
graph_height: 200
graph_time_ranges:
  - label: "1h"
    seconds: 3600
  - label: "6h"
    seconds: 21600
  - label: "12h"
    seconds: 43200
  - label: "24h"
    seconds: 86400
